### ISSUE TITLE
Il n'y a pas de croissants

### ISSUE THREAD

**Issue by ReimuA** [titouancreach/azure-sb-function#1]
on m'a promis des croissants.

**Comment by corent105** [comment]
Oui les croissants ne sont pas valides

**Comment by ReimuA** [comment]
Day 3 of no croissants february

**Comment by corent105** [comment]
Je pense que le problèmes de croissants vient des cookies. 

![image](https://user-images.githubusercontent.com/47932272/152501886-adea5bd6-0157-41aa-b0bf-1e968fd2b91c.png)
